[package]
name = "game"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[dependencies]
avian2d = "0.3.1"
bevy = "0.16.1"
web-sys = "0.3.77"
